project: 
  type: book

book: 
  page-navigation: true
  title: "SEDAR 84" 
  site-url: "https://solid-adventure-7j5gko7.pages.github.io/" 
  repo-url: "https://github.com/SEFSC/SEFSC-SEDAR-CR-84-STX-SLP-2022"
  repo-actions: [edit, source, issue]
  favicon: assets/favicon.ico
  downloads: [pdf, docx]
  search: true
  author:
    - name: Southeast Fisheries Science Center
      affiliations:
        - name: NOAA Fisheries
  chapters:
    - index.qmd
    - content/background.qmd
    - content/data.qmd
    - content/methods.qmd
    - content/references.qmd
    - content/results.qmd

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://raw.githubusercontent.com/nmfs-opensci/assets/main/logo/nmfs-opensci-logo3.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nmfs-opensci.github.io
        text: "NMFS Open Science"
    style: "docked"
    search: true
    collapse-level: 1

bibliography: [content/references.bib]
csl: apa.csl

execute:
  echo: false
  code-overflow: wrap
  
include-in-header: 
  - text: |
      \raggedright
      \usepackage{caption}
      \captionsetup[table]{justification=raggedright, format=plain, indention=1em, singlelinecheck=false}
      \captionsetup[figure]{justification=raggedright, format=plain, indention=1em, singlelinecheck=false}

format:
  pdf:
    toc: true
    toc-depth: 3
  docx:
    toc: true
    toc-depth: 3
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: [cosmo, assets/theme.scss] 
    toc: true
    toc-depth: 3

filters:
  - assets/include-files.lua
  - quarto

# Comment next 2 lines if the PDF is having trouble
# metadata-files:
#   - _frontmatter.yml