---
title: "Data-Informed Modeling Decisions"
---

The data available for use in the current assessment are documented in the SEDAR 84 US Caribbean Stoplight Parrotfish St. Croix Data Workshop Report [@sedar2024]. Provided here is a summary of those data with a focus on the associated model configurations explored using Stock Synthesis. Throughout this report, bolded text is used to highlight and summarize the model settings and configurations relevant to the various phases of model development.

Additional details for each data input are available in their respective references:

1.  **Landings** from self-reported commercial fisher logbooks [@martínezrivera2024]
2.  **Length compositions** from shore-based port sampling [@godwin2024]
3.  **Length compositions** from a fishery-independent survey of reef fish [@grove2024]
4.  **Index of abundance** from a fishery-independent survey of reef fish [@grove2024]
5.  **Life history information** from otolith analysis and gonad histology [@riverahernández2024]

**Based on the available data, the assessment was configured with one area, one season, one commercial fleet, and one fishery-independent survey.**

## Commercial Fleet Data {#sec-data-fleet}

### Catch {#sec-data-fleet-catch}

The catch data for the commercial fleet came from the Caribbean Commercial Logbook program [@martínezrivera2024]. Beginning in 1996, part of the commercial landings was reported by species groups (e.g., snappers, groupers, parrotfishes, surgeonfishes, etc.), and by gear (hook and line, gill net, SCUBA, trap, etc.). All commercial fishery data reports included species groups beginning in 1998. In July of 2011, commercial landings were reported by species and gear. Various diving gears were combined to establish a dive gear group. 

The catch of Stoplight Parrotfish in St. Croix from the dive group made up 80% of the reported landings. For the SEDAR 84 stock assessment, all gears (dive and other) were included into a single commercial fleet (@tbl-catch). Potential outliers discussed during the assessment webinars were investigated and retained as valid trips.

In the SEDAR 84 Stock Synthesis models, **the catch was input as biomass (in metric tons) and was treated as if it occurred over an entire fishing season; i.e., each fishing year.** 

The years of the available species-specific self-reported commercial fisher logbook landings and effort data determined the start and end years of the Stock Synthesis models. **The start and end years of the model were 2012 and 2022, respectively.** 

It is important to note that the stock was not unexploited at the start year of the available catch time series. The commercial landings of all parrotfish species reported in St. Croix in 2012 was undergoing a meaningful decline. From 1996 to 2009, combined landings of all parrotfish consistently exceeded 200,000 pounds, peaking in 2006 at over 430,000 pounds. Landings dropped sharply after 2010 and have remained below 100,000 pounds since 2013, with particularly low values after 2017 (@sedar2024, Table 3.1.3). Initial F was estimated for the commercial fleet and a corresponding initial equilibrium catch. A common option to define reference point for the initial equilibrium catch is to use the geometric mean of the first three years of available catches. However, because of the decline preceding the start year of the assessment, the assessment panel agreed on using a value higher than the geometric mean of the first three years. **The initial equilibrium catch was configured in initial runs as 30 metric tons**, a little over twice the geometric mean of the catches from 2012 - 2014.

**The input standard error for the landings was set to 0.3.** When implemented with few data inputs, Stock Synthesis strongly prioritizes fitting the annual landings time series, often replicating the observed values almost exactly, particularly when small standard errors (e.g., 0.01) are used. The initial configurations with low input uncertainty resulted in the model tightly fitting both the observed landings and the input initial equilibrium catch. To allow the model greater flexibility in estimating the initial equilibrium catch, and avoid anchoring it too closely to the input value, a higher standard error of 0.3 was specified for the initial equilibrium catch. This increased uncertainty enables the model to balance trade-offs among other data sources and internal dynamics when estimating initial conditions. A description of the sequential model configurations and development process is provided later in this report.

A higher standard error of 2 was explored as part of the sensitivity analysis to evaluate the influence of extreme uncertainty in the initial equilibrium catch input. This value was intentionally selected to represent a scenario with minimal confidence, allowing the model to substantially down-weight this input and reveal how strongly model outputs depend on the assumed precision of the initial equilibrium catch.

Commercial discards reported by calendar year by @martínezrivera2024 were not significant and based on the nature of spearfishing, the predominant dive gear. Based on expert judgment and available information, discards of Stoplight Parrotfish in the St. Croix commercial fishery are considered negligible, with minimal associated mortality (@sedar2024). Given the expectation of low discard rates, **discards were not explicitly included in the model inputs or parameterized through a retention function. The assessment assumed full retention of catch.**

Alternative model configurations associated with the commercial fleet data are described later in this report. They included:

-   The initial equilibrium catch was explored via likelihood profiling.
-   A higher standard error of 2 was explored via sensitivity analysis.

### Length Composition {#sec-data-fleet-size}

Gear-specific annual length frequencies for the commercial fleet came from the commercial shore-based port-sampling Trip Interview Program (TIP) [@godwin2024]. The Trip Interview Program manages data from the U.S. Virgin Islands collected by Division of Fish and Wildlife personnel. Port sampling personnel collect length and weight data from fish landed by commercial fishing vessels, along with information about general area of capture and gear used. Data collection began in 1983 with frequent updates in best practices; the latest being in 2017. The Stoplight Parrotfish length data from St. Croix included 29,582 length observations across 1,028 unique port sampling interviews.

Although the catch data can be separated into dive and non-dive related gears, 98% of the length measurements for St. Croix Stoplight Parrotfish from 2012-2022 were associated with diving. Those data were used to characterize the commercial fleet's length-based selectivity pattern. Since multiple fish length measurements can be obtained from a single sampled trip, each length does not represent an independent observation. **The relative model weighting of the commercial fleet length composition data was based on the number of trips sampled**. 

From 2012 - 2022, the data included 1,033 shore-based length measurements obtained across 66 trips. Five trips were flagged and removed as potential outliers with unusually large lengths. **Due to low sample sizes of both fish and trips, the fishery-dependent commercial fleet length composition data were collapsed across all years 2012-2022** by implementing the super-period approach in Stock Synthesis.

**The Trip Interview Program length compositions of the commercial fleet were assumed to be representative of the total catch.** Although a federal minimum size limit exists, it does not apply in USVI territorial waters extending from land to 3 nautical miles offshore. Discussion at the data workshop emphasized that the federal regulations do not conclusively affect retention.

**A double normal function was used to model the relative vulnerability of capture by length for the commercial fleet.** However, only two parameters were estimated, effectively describing a logistic selectivity for the commercial fleet. The double normal function allows for domed or logistic selectivity. It combines two normal distributions; the first describes the ascending limb, while the second describes the descending limb. Domed selectivity was not explored for St. Croix Stoplight Parrotfish. However, achieving the logistic shape with the double normal Stock Synthesis pattern facilitated model configurations for SEDAR 84. The two parameters used to achieve a logistic selectivity shape were the length associated with peak selectivity and the width of the ascending limb.

## Survey Data {#sec-data-survey}

### Index of Abundance {#sec-data-survey-index}

The National Coral Reef Monitoring Program (NCRMP) supports reef fish sampling on hard-bottom habitats from 0 to 30 meters depth [@grove2021]. In St. Croix, sampling began in 2001 and was conducted every year from 2001 to 2012 and then every other year starting in 2015. The data used in SEDAR 84 were from nonconsecutive years during 2012 - 2022 when the survey was conducted island-wide. Data collected prior to 2017 were calibrated to account for a transition from belt transect to a cylinder survey method.

Annual mean density and associated standard errors for SEDAR 84 were provided by @grove2024. In Stock Synthesis, the time series of mean density across all observed lengths **were input as an index in numbers with a lognormal error distribution**. The associated length composition data, described in the following subsection, suggested that **the index reflected the abundance of juveniles and adults**.

### Length Composition {#sec-data-survey-size}

The three most recent years (2017, 2019, 2021) of the National Coral Reef Monitoring Program survey in St. Croix provided counts by individual lengths estimated to the nearest centimeter. However, before 2017 the length observations were collected in 5-centimeter bins. **The length data inputs for both the commercial fleet and the three years of the survey with 1-centimeter length measurements were binned to match the survey's 2012 and 2015 5-centimeter bins.**

A large proportion of small fish were observed in the National Coral Reef Monitoring Program survey. **The smallest two bins, (1 - 6 centimeters) and (6 - 11 centimeters), were collapsed into a single bin (1 - 11 centimeters).**

Since multiple fish can be observed during a single dive, individual lengths are not independent observations. **The relative model weighting of the National Coral Reef Monitoring Program survey length composition data across years was based on the number of paired dives.**

The length composition data provided reasonable support that younger and older fish were available to the National Coral Reef Monitoring Program survey. **Selectivity for the National Coral Reef Monitoring Program survey was fixed at 1 for all lengths.**

Models were initially configured in Stock Synthesis with length composition data aggregated across the available years for each source of length data. Investigation of additional model configurations proceeded stepwise from the simplest configuration to those of moderate complexity. The steps included the inclusion of annual fishery-independent length compositions. The sequential model configurations are described later in this report.

## Life History Data {#sec-data-biology}

The life history data used in the assessment included longevity-informed natural mortality, growth, length-weight, and maturity analyzed from 1,801 samples of Stoplight Parrotfish collected across the U.S. Caribbean from 2013 to 2023 [@riverahernández2024]. The largest fish was 43.3 centimeters fork length and the oldest was 20 years old.

Based on the available information, **the Stoplight Parrotfish population was modeled from age 0 through age 20, and from 0 to 41-centimeters fork length, in 1-centimeter bins, with the largest values for each as plus groups.**

Note that SS3 allows the length bins of the data inputs to be larger than the bins used in the population model. **Although the bin size of all the length data inputs were large (≥ 5 centimeters), the model's simulated population bin size was 1-centimeter bins.** When the population is modeled at a higher resolution concerning bin size, the likelihood function, which aims to match the observed data inputs and the simulated population estimates, operates at the resolution of the data inputs.

### Growth {#sec-data-growth}

The SS3 growth formulation requires five parameters:

-   Length at the youngest age
-   Length at the maximum age
-   Von Bertalanffy growth parameter (K)
-   Coefficient of variation at the youngest age
-   Coefficient of variation at the maximum age

**Parameter estimates for Von Bertalanffy growth parameter (K) and the length at maximum age (L~∞~) were based on 1,649 samples of Stoplight Parrotfish collected across the U.S. Caribbean from 2013 to 2023 [@riverahernández2024].** When t~0~ was fixed to -0.06, K was 0.39 and L~∞~ was 33.2 centimeters fork length. When t~0~ was estimated, it was -0.52, K was 0.33, and L~∞~ was 33.8 centimeters fork length. 

The SEDAR 84 assessment models were configured using the parameter estimates associated with the fixed t~0~. Furthermore, **the estimated length at age zero from otolith analysis by @riverahernández2024 was modified in Stock Synthesis so that the length of the youngest age, age 0, was set to zero.** Without this modification, the model would be unable to fit the substantial amounts of small (\<10cm) Stoplight Parrotfish observed in the survey length composition data.

**Coefficients of variation for both younger and older ages were initially set to 0.15.** Ideally, growth coefficients of variation should be derived from observed length-at-age data, however, the assumed values are consistent with species of moderate growth variability [@ono2015; @schemmel2022]. 

Alternative model configurations associated with the growth data are described later in this report. They included:

-   A higher growth coefficient of variation of 0.25 for younger ages was explored via sensitivity analysis.

### Morphometric Conversion {#sec-data-morphometric}

The relationship between weight in grams and length in millimeters provided by @riverahernández2024 was converted to weight in grams and length in centimeters and used as a fixed model input. **The length-weight relationship was W = 3.18 x 10^-5^ * L^2.9^, with weight (W) in kilograms and length (L) in centimeters.**

### Maturity, Fecundity, and Hermaphroditism {#sec-data-reproduction}

**Maturity was modeled as a logistic function.** Parameter estimates for maturity were based on 1,801 samples of Stoplight Parrotfish collected across the U.S. Caribbean from 2013 to 2023 [@riverahernández2024]. **The fecundity of Stoplight Parrotfish was estimated with a proxy (body weight \* maturity at age).**

Protogynous hermaphroditism was parameterized into the SS3 assessment framework in two ways. **The initial method to model hermaphroditism in Stock Synthesis used the mean age of transition, an associated standard deviation, and a maximum transition rate input as fixed parameters in a two-sex model.** Additionally, the sex ratio between female and male fish at recruitment was 1, such that all individuals were recruited as females. Although this approach allows for the explicit modeling of numbers by sex and age over time, it could not capture the early age at transition and the overlap of both sexes directly observed across the range of ages studied by @riverahernández2024.

**A second method for parameterizing hermaphroditism was explored as a sensitivity analysis.** It involved using a female-only model and accounting for sex transition to males as a reduction in fecundity. A fecundity-at-age vector derived from a logistical fit to the @riverahernández2024 sex-at-age data was multiplied by maturity-at-age and fecundity-at-age. A caveat of using a single-sex model is that the exclusion of males does not allow for any potential sperm limitation. Although protogynous hermaphrodites tend to have sex ratios skewed towards males at larger lengths, the largest and oldest Stoplight Parrotfish observed by @riverahernández2024 were female.

### Stock Recruitment {#sec-data-sr}

**A Beverton-Holt stock-recruit function was used to parametrize the relationship between spawning output and resulting recruitment of age-0 fish.** The stock-recruit function requires three parameters:

-   Steepness (h) characterizes the initial slope of the ascending limb (i.e., the fraction of recruits produced at 20% of the unfished spawning biomass).
-   The virgin recruitment (R0; estimated in log space) represents the asymptote or unfished recruitment levels.
-   The variance term (sigma R) is the standard deviation of the log of recruitment and describes the amount of year-to-year variation in recruitment.

Only the virgin recruitment (R0) was estimated. **Sigma R and steepness were fixed at 0.7 and 0.99, respectively.** The 0.7 sigma R reflects slightly high variation in recruitment. A value of 0.6 is a moderate level of recruitment variability, with lower values indicating lower variability and more predictable year-to-year recruitment. The primary assumption for steepness was that this stock is not a closed population, so recruitment may not be strongly tied to the local spawning stock biomass. **In initial model configurations, annual deviations from the stock-recruit function were not estimated.** Steepness and R0 were explored via likelihood profiling.

**Continuous recruitment was parameterized in SS3 using four settlement events.** Equal proportions of recruits were assigned to each settlement event, and they were spaced such that recruitment would happen in months 1, 4, 7, and 10. This allowed growth to be staggered, reflecting a closer approximation of the observed stock dynamic of year-round spawning activity.

### Maximum Age and Natural Mortality {#sec-data-m}

Empirical estimates of natural mortality (M) can be derived using life history information such as longevity, growth, and maturity. For this assessment, the Natural Mortality Tool was used to estimate M [@cope2022]. Various methods were explored, incorporating factors such as maximum age, the Von Bertalanffy growth parameter (K), theoretical age at length zero (t~0~), asymptotic length (L~∞~), and age at 50% maturity.

Inputs for the Natural Mortality Tool were sourced from @riverahernández2024, which reported a maximum age of 20 years for Stoplight Parrotfish in the U.S. Caribbean. However, the mean age of 1,649 sampled fish was 5.4 years, with fewer than 1% of aged individuals reaching 13 years or older. A lower maximum age of 9 years was observed (with a suggested maximum lifespan of 12 years) for stoplight parrotfish collected in 1995-2000 from Bahamas, Panama, Venezuela, and Barbados, but fish analyzed for age were limited to collections from depths ≤ 15 m [@choat2003]. In contrast, a study from Bonaire utilized repeated visual censuses that included marked fish to estimate growth and mortality rates and estimated that stoplight parrotfish can attain a maximum age of over 25 years [@vanrooij1997]. @choat2003 interpreted results from Van Rooji and Veideler (1997) as follows: “Although no estimate of maximum lifespan is given, their survival curves suggest a maximum age of 30 years.”.

More broadly across the Caribbean, a lower maximum age of 9 years was observed, with a suggested maximum lifespan of 12 years. In contrast, a tagging study in Bonaire indicated a potential maximum longevity of 30 years [@choat2003].

@tbl-m summarizes these studies and the empirical methods used to estimate M based on available life history data. The primary approach for determining natural mortality in this assessment was longevity-based [@hamel2022]. Although additional methods incorporating growth and maturity were explored using the Natural Mortality Tool, their applicability remains uncertain due to the species’ sex-changing nature. Specifically, the methods Hamel_K, Jensen_k 1, Jensen_k 2, Then_VBGF, Jensen_Amat, and Ri_Ef_Amat do not account for protogynous hermaphroditism [@hamel2015; @jensen1996; @jensen1997; @then2015; @rikhter1976]. Notably, immature males have not been documented for Stoplight Parrotfish and the SEDAR 84 available inputs of age at 50% maturity reflect only the sexual maturity of females, while the Von Bertalanffy growth parameters (K), t0, and asymptotic length were fit across males, females, and transitional individuals combined (@riverahernández2024).

**A natural mortality value of 0.27 was used in the initial model runs**. This value corresponds with the maximum age of 20 years reported by @riverahernández2024. Model configurations incorporating an alternative M value associated with a higher maximum age were explored through sensitivity analyses, which are discussed later in this report.

## Summary of Data-Informed Modeling Configurations {#sec-data-summary}

-   Based on the available data, the assessment was configured with one area, one season, one commercial fleet, and one fishery-independent survey.

### Commercial Fleet {#sec-data-summary-fleet}

-   The catch was input as biomass (in metric tons) and was treated as if it occurred over an entire fishing season; i.e., each fishing year.

-   The start and end years of the model were 2012 and 2022, respectively.

-   Based on expert input and limited data, discards were not modeled. The assessment assumed full retention of catch.

-   The input standard error for the landings was set to 0.3.

    -   A lower standard error of 0.1 was explored via sensitivity analysis.

-   The initial equilibrium catch was configured in initial runs as 30 metric tons.

    -   The initial equilibrium catch was explored via likelihood profiling.

-   The relative model weighting of the commercial fleet length composition data was based on the number of trips sampled.

-   Due to low sample sizes, the fishery-dependent commercial fleet length composition data were combined across all years.

-   The length compositions of the commercial fleet were assumed to be representative of the total catch.

-   A double normal function was used to model the relative vulnerability of capture by length for the commercial fleet.

### Survey {#sec-data-summary-survey}

-   The index reflected the abundance of juveniles and adults.

-   The survey was configured as an index in numbers with a lognormal error distribution

-   The relative model weighting of the survey length composition data across years was based on the number of paired dives.

-   The length data inputs for both the commercial fleet and the three years of the survey with 1-centimeter length measurements were binned to match the survey's 2012 and 2015 5-centimeter bins.

-   Although the bin size of all the length data inputs were large (5 centimeters), the model's simulated population bin size was 1-centimeter bins.

-   The smallest two bins, (1 - 6 centimeters) and (6 - 11 centimeters), were collapsed into a single bin (1 - 11 centimeter). 

-   Selectivity for the survey was fixed at 1 for all lengths. 

### Life History {#sec-data-summary-biology}

-   The Stoplight Parrotfish population was modeled from age 0 through age 20, and from 0 to 41-centimeters fork length, in 1-centimeter bins, with the largest values for each as plus groups.

-   Parameter estimates for Von Bertalanffy growth parameter (K) and the length at maximum age (L~∞~) were based on samples of Stoplight Parrotfish collected across the U.S. Caribbean from 2013 to 2023.

-   The estimated length at age zero from otolith analysis by @riverahernández2024 was modified in Stock Synthesis so that the length of the youngest age, age 0, was set to zero.

-   Coefficients of variation for both younger and older ages were initially set to 0.15.

    -   A higher growth coefficient of variation of 0.25 for younger ages was explored via sensitivity analysis.

-   The length-weight relationship was W = 3.18 x 10\^-5 L\^ 2.9, with weight in kilograms and length in centimeters.

-   A natural mortality value of 0.27 was used in the initial model runs.

    -   Alternative M values were explored through sensitivity analyses.

-   Maturity was modeled as a logistic function.

-   The fecundity of Stoplight Parrotfish was estimated with a proxy (body weight \* maturity at age).

-   The initial method to model hermaphroditism used the mean age of transition, an associated standard deviation, and a maximum transition rate input as fixed parameters in a two-sex model.

    -   A second method for parameterizing hermaphroditism (a female-only model and accounting for sex transition to males as a reduction in fecundity) was explored as a sensitivity analysis.

-   A Beverton-Holt stock-recruit function was used to parametrize the relationship between spawning output and resulting recruitment of age-0 fish.

-   Sigma R and steepness were fixed at 0.7 and 0.99, respectively.

-   In initial model configurations, annual deviations from the stock-recruit function were not estimated.
    
-   Continuous recruitment was parameterized in SS3 using four settlement events.
