---
  title: "Assessment Process Research Recommendations"
---

To mitigate some of the data uncertainties it is recommended to:

-   Expand fishery-independent survey time series and resolution (e.g., retain and use 1-cm length bin data where available).

-   Further evaluate natural mortality and growth assumptions. Collect and analyze additional life history data to reduce uncertainty around growth and natural mortality rates.

-   Conduct focused research on historical catches and fishing history to inform and constrain early model conditions.

-   Consider using simpler production models or age-structured models with fixed selectivity to isolate and evaluate different data inputs.

-   Develop and evaluate model ensembles or uncertainty grids to guide catch advice under different plausible scenarios.

-   Investigate stock connectivity to better understand local versus regional recruitment dynamics and their implications for informing steepness.

-   Re-examine multiple indicator approach for the Parrotfish Two management unit given that SEDAR 84 only comprehensively evaluated data for *Sparisoma viride*.

-   Research methods, including simulations, to “right-size” model complexity to match data availability, avoiding overparameterization in data-limited contexts.

-   Support Management Strategy Evaluations that are robust to key uncertainties to guide harvest advice.

-   Ensure the continuation of fishery-independent survey programs (e.g., National Coral Reef Monitoring Program) with consistent spatial and temporal coverage.

-   Maintain and expand commercial catch monitoring programs. Expand port sampling and other fishery-dependent data collection to fill gaps in length composition and effort data.