---
title: "Modeling Framework"
---

**Stock Synthesis was the modeling approach applied in this assessment because of its compatibility with the available data and consistent with standard practices.**

Stock Synthesis is a statistical catch-at-age model that uses a population model, an observation model, and an estimation model and applies a likelihood function in the estimation process [@methot2020]. Stock Synthesis, commonly referred to as SS3, has been applied extensively worldwide for stock assessment evaluations [@methot2013]. It has also been used for previous data-limited and data-moderate SEDAR assessments, including the SEDAR 57 assessments and subsequent updates for Caribbean Spiny Lobster, and the SEDAR 80 assessments for Queen Triggerfish [@sedar2019; @sedar2022]. The Stock Synthesis modeling framework is a compatible tool for SEDAR stock assessments for species in the U.S. Caribbean because it can accommodate a wide range of model complexities, from data-limited to highly detailed assessments [@cope2024]. Stock Synthesis allows for the characterization of stock, fishing fleet, and survey dynamics through various parameters, which can be either fixed based on external data or estimated when sufficient assessment data are available. Furthermore, Stock Synthesis is particularly useful for incorporating complex biological dynamics, such as hermaphroditism and continuous recruitment, which are critical for accurately assessing St. Croix Stoplight Parrotfish. Hermaphroditism directly influences reproductive potential and stock sustainability, making it essential to model sex transitions appropriately. Additionally, assuming a single pulse of annual recruitment oversimplifies the population structure by failing to account for the continuous presence of multiple size classes in the stock. Continuous recruitment modeling enables the assessment to recognize that fish born within the same calendar year can reach vulnerable sizes at different times, affecting catch dynamics and stock projections. Finally, R packages such as R4ss and SS3diags allow critical evaluations of model reliability and facilitate model comparisons. across alternative assumptions and parameter values, to evaluate the sensitivity of results to modeling decisions implemented with the Stock Synthesis framework [@taylor2021; \@carvalho2021]. R4SS provides visualization and diagnostic tools to summarize and interpret fit, convergence, and key output metrics. SS3diags focuses on retrospective analyses, hind-casting, and residual pattern evaluations. The integration of these tools allows rigorous uncertainty analysis, streamlined sensitivity analyses, and enhanced transparency in decision-making.
