on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        
      - name: Set up R (needed for Rmd)
        uses: r-lib/actions/setup-r@v2
              with:
                packages:
                  any::knitr
                  any::rmarkdown
                  any::flextable
                  any::here
                  any::dplyr

      - name: Install packages (needed for Rmd)
        run: Rscript -e 'install.packages(c("here", "systemfonts", "textshaping", "rmarkdown", "knitr", "jsonlite", "gdtools", "officer", "ragg", "flextable", "dplyr"))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      # add software dependencies here

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
